### ISSUE TITLE
HTML entities previous and next

### ISSUE THREAD

**Issue by jacob-v-dam** [luis-almeida/jPages#4]
If you want to set the pervious and next to an HTML entity you will get an error.

The javascript:

``` $(function(){
                            $('div.pagination').jPages({
                                containerID : 'itemHolder',
                                perPage : 9,
                                previous : '&lsaquo;',
                                next : '&rsaquo;'
                            });
                        });
```

And the error inside jQuery 1.7.2 (it also happens in 1.7.1):

> Syntax error, unrecognized expression: &lsaquo;

**Comment by luis-almeida** [comment]
I wasn't aware of this. Thanks for pointing it out!
But if you use the "decimal" or even the "hex" entity code it works fine:

http://jsfiddle.net/pLUrS/

**Comment by jacob-v-dam** [comment]
Thanks for this solution.
