### ISSUE TITLE
jPages is not a function

### ISSUE THREAD

**Issue by KlymSerhii** [luis-almeida/jPages#51]
Hi, 
I have this kind of error "Uncaught TypeError: $(...).jPages is not a function". Why this error could appear?
(Everithing done according to your guide(http://luis-almeida.github.io/jPages/))

**Comment by narendrasharma** [comment]
This is a not issue of jpages.
Its a issue of jquery library..
Jpages works with jquery library.make sure you have included after jquery.
We should not count it as issue.
you should be on stackoverflow to find your answer not on github.so please don't increase issue list.
Thanks for anticipation.
